### ISSUE TITLE
How to use markdown pages?

### ISSUE THREAD

**Issue by vecna** [uradotdesign/makhno-website#2]
I was trying to fill up the content, for example, of About and Methodology, by editing `content/methodology/_index.md`

But I'm seeing that the rendered HTML is not the one from the `content/methodology/_index.md` but rather it comes from `layouts/_default/methodology.html`, so I think, somehow, that layout should include the `Content` of the Markdown.

```
$ cat methodology.html 
{{ define "main" }}

<section>
    <div class="somethong">
        <h1>Methodologjy</h1>
    </div>
</section>

{{ end }}
```

Thanks!

**Comment by AnXh3L0** [comment]
Hi @vecna, I fixed this issue as well and introduced a simpler way to fill the markdown pages, you can now just add markdown on any individual [pagename].md file, and it will show up on its own single page. Closing as fixed/improved.
