### ISSUE TITLE
Javascript fault in homepage

### ISSUE THREAD

**Issue by vecna** [uradotdesign/makhno-website#3]
![image](https://github.com/uradotdesign/makhno-website/assets/89555/89055aa3-edfb-48d6-9bbb-4901616ab764)

The first is triggered when the homepage loads, the second when the `Advanced Options` menu is clicked.

**Comment by AnXh3L0** [comment]
Thanks @vecna, I found the culprits and I'm working to fix them now. Keeping this open until I commit the fix.

**Comment by AnXh3L0** [comment]
Hi again @vecna, I fixed the JS errors on the homepage via the last commit, closing this as fixed.
